# Generated by Django 3.2.8 on 2022-03-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0021_delete_feed'),
        ('users', '0010_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_post',
            field=models.ManyToManyField(blank=True, related_name='saved_post', to='homeapp.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_tell',
            field=models.ManyToManyField(blank=True, related_name='saved_tell', to='homeapp.Tell'),
        ),
    ]
