# Generated by Django 3.2.8 on 2022-03-28 19:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0021_delete_feed'),
        ('users', '0011_auto_20220328_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_post',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_tell',
        ),
        migrations.CreateModel(
            name='SaveTell',
            fields=[
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('tell', models.ManyToManyField(blank=True, related_name='saved_post', to='homeapp.Tell')),
            ],
        ),
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('post', models.ManyToManyField(blank=True, related_name='saved_post', to='homeapp.Post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
