# Generated by Django 3.2.8 on 2022-03-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220328_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savetell',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='savetell',
            name='tell',
        ),
        migrations.DeleteModel(
            name='SavePost',
        ),
        migrations.DeleteModel(
            name='SaveTell',
        ),
    ]
