# Generated by Django 3.2.8 on 2022-03-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0025_auto_20220329_0534'),
        ('users', '0016_auto_20220328_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_post',
            field=models.ManyToManyField(blank=True, related_name='saved_post', to='homeapp.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_tell',
            field=models.ManyToManyField(blank=True, related_name='saved_tell', to='homeapp.Tell'),
        ),
    ]
