# Generated by Django 3.2.8 on 2022-03-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220330_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollower',
            old_name='followed_by',
            new_name='follower_to',
        ),
    ]
