# Generated by Django 3.2.8 on 2022-03-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_followed_by_userfollower_follower_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollower',
        ),
    ]
