# Generated by Django 3.2.8 on 2022-03-31 21:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_userfollower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollower',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ['-created']},
        ),
        migrations.AlterUniqueTogether(
            name='userfollower',
            unique_together={('me', 'follower_to')},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('me', 'following')},
        ),
        migrations.DeleteModel(
            name='friends',
        ),
    ]
