# Generated by Django 3.2.8 on 2022-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220331_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
