# Generated by Django 3.2.8 on 2022-04-13 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0024_profile_activity_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('last_seen', models.BooleanField(default=True)),
                ('stories_privacy', models.BooleanField(default=True)),
                ('read_reciet', models.BooleanField(default=True)),
                ('no_response_top_all', models.BooleanField(default=False)),
                ('no_response_top_unread', models.BooleanField(default=True)),
                ('dark_mode_chat', models.BooleanField(default=False)),
                ('private_account', models.BooleanField(default=False)),
                ('comments', models.BooleanField(default=True)),
                ('dark_mode_account', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
