# Generated by Django 3.2.8 on 2022-04-13 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Settings'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='comments',
        ),
        migrations.AddField(
            model_name='settings',
            name='comments_privacy',
            field=models.CharField(default='Everyone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='comments_privacy_except',
            field=models.ManyToManyField(related_name='comment_privacy_except', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settings',
            name='stories_privacy_except',
            field=models.ManyToManyField(related_name='story_privacy_except', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settings',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settings',
            name='stories_privacy',
            field=models.CharField(default='Everyone', max_length=20, null=True),
        ),
    ]
