# Generated by Django 3.2.8 on 2022-04-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20220413_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='no_response_top_all',
            new_name='top_all',
        ),
    ]
