# Generated by Django 3.2.8 on 2022-04-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_rename_no_response_top_all_settings_top_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='no_response_top_unread',
            new_name='top_unread',
        ),
    ]
