# Generated by Django 4.0.4 on 2022-04-14 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0030_rename_no_response_top_unread_settings_top_unread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='comments_privacy_except',
            field=models.ManyToManyField(blank=True, related_name='comment_privacy_except', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settings',
            name='stories_privacy_except',
            field=models.ManyToManyField(blank=True, related_name='story_privacy_except', to=settings.AUTH_USER_MODEL),
        ),
    ]
