# Generated by Django 4.0.4 on 2022-06-02 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_profile_bio_alter_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_msg_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 2, 6, 54, 17, 397567), null=True),
        ),
    ]
