# Generated by Django 4.0.4 on 2022-06-04 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_profile_unread_msg_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 4, 10, 50, 7, 472410), null=True),
        ),
    ]
