# Generated by Django 4.0.4 on 2022-06-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_profile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='online',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_post',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_tell',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seen_post',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seen_tell',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
