# Generated by Django 4.0.4 on 2022-06-19 19:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0053_remove_profile_activity_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UProfile',
        ),
    ]
