# Generated by Django 4.0.4 on 2022-06-19 19:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0046_post_sharers_post_sharers_count_tell_sharers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0055_alter_uprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True, unique=True)),
                ('img', models.ImageField(default='icons/user.png', upload_to='profiles/')),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 19, 20, 31, 34, 990878), null=True)),
                ('verified', models.BooleanField(default=False)),
                ('activity_count', models.PositiveSmallIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('saved_post', models.ManyToManyField(blank=True, related_name='saved_post', to='homeapp.post')),
                ('saved_tell', models.ManyToManyField(blank=True, related_name='saved_tell', to='homeapp.tell')),
                ('seen_post', models.ManyToManyField(blank=True, to='homeapp.post')),
                ('seen_tell', models.ManyToManyField(blank=True, to='homeapp.tell')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
