# Generated by Django 4.0.4 on 2022-06-19 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_alter_uprofile_id_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 19, 20, 35, 25, 61765), null=True),
        ),
        migrations.DeleteModel(
            name='UProfile',
        ),
    ]
