# Generated by Django 3.2.8 on 2022-04-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0002_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
