# Generated by Django 3.2.8 on 2022-04-09 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0003_auto_20220409_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='messagesapp.message')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
