# Generated by Django 3.2.8 on 2022-04-09 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagesapp', '0004_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Body'},
        ),
        migrations.AddField(
            model_name='message',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('owner', 'recipient')},
        ),
    ]
