# Generated by Django 3.2.8 on 2022-04-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0005_auto_20220409_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated']},
        ),
    ]
