# Generated by Django 3.2.8 on 2022-04-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messagesapp.message'),
        ),
    ]
