# Generated by Django 3.2.8 on 2022-04-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0008_body_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='owner',
        ),
    ]
