# Generated by Django 3.2.8 on 2022-04-09 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagesapp', '0010_body_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
