# Generated by Django 3.2.8 on 2022-04-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0011_body_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
