# Generated by Django 3.2.8 on 2022-04-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0012_message_last_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='last_msg',
        ),
    ]
