# Generated by Django 3.2.8 on 2022-04-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0014_message_last_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='last_body',
        ),
    ]
