# Generated by Django 3.2.8 on 2022-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0015_remove_message_last_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_body',
            field=models.ManyToManyField(null=True, related_name='last_body', to='messagesapp.Body'),
        ),
    ]
