# Generated by Django 3.2.8 on 2022-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0016_message_last_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_body',
            field=models.ManyToManyField(blank=True, related_name='last_body', to='messagesapp.Body'),
        ),
    ]
