# Generated by Django 3.2.8 on 2022-04-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0018_remove_message_last_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_body', to='messagesapp.body'),
        ),
    ]
