# Generated by Django 3.2.8 on 2022-04-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0019_message_last_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='request_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_body',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_body', to='messagesapp.body'),
        ),
    ]
