# Generated by Django 3.2.8 on 2022-04-11 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0020_auto_20220411_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messagesapp.message'),
        ),
    ]
