# Generated by Django 3.2.8 on 2022-04-12 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0021_alter_body_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_of_last_message',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 12, 20, 2, 18, 253233), null=True),
        ),
    ]
