# Generated by Django 3.2.8 on 2022-04-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0022_message_date_of_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_of_last_message',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
