# Generated by Django 3.2.8 on 2022-04-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0023_alter_message_date_of_last_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_of_last_message',
            new_name='subdate',
        ),
    ]
