# Generated by Django 4.0.4 on 2022-04-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0025_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='paticipants',
            new_name='participants',
        ),
    ]
