# Generated by Django 4.0.4 on 2022-06-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0026_rename_paticipants_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
