# Generated by Django 4.0.4 on 2022-06-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0045_post_tellers_count_tell_tellers_count'),
        ('messagesapp', '0027_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='msg_on_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_post', to='homeapp.post'),
        ),
        migrations.AddField(
            model_name='body',
            name='msg_on_tell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_tell', to='homeapp.tell'),
        ),
    ]
