# Generated by Django 4.0.4 on 2022-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0028_body_msg_on_post_body_msg_on_tell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
