# Generated by Django 3.2.8 on 2022-03-22 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0002_tell_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketell',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='liketell',
            unique_together={('owner', 'like')},
        ),
    ]
