# Generated by Django 3.2.8 on 2022-03-22 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0003_auto_20220322_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentontell',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='liketell',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AddField(
            model_name='tell',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
