# Generated by Django 3.2.8 on 2022-03-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_alter_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeTell',
        ),
    ]
