# Generated by Django 3.2.8 on 2022-03-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_auto_20220325_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='tell',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
