# Generated by Django 3.2.8 on 2022-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='post',
            field=models.ManyToManyField(blank='True', to='homeapp.Post'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='tell',
            field=models.ManyToManyField(blank='True', to='homeapp.Tell'),
        ),
    ]
