# Generated by Django 3.2.8 on 2022-03-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_auto_20220325_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentonpost',
            name='comment',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tell',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
