# Generated by Django 3.2.8 on 2022-03-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0020_alter_feed_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
