# Generated by Django 3.2.8 on 2022-03-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0024_savepost_savetell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savepost',
            old_name='profile',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='savetell',
            old_name='profile',
            new_name='owner',
        ),
    ]
