# Generated by Django 3.2.8 on 2022-03-29 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0025_auto_20220329_0534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savepost',
            unique_together={('owner', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='savetell',
            unique_together={('owner', 'tell')},
        ),
    ]
