# Generated by Django 3.2.8 on 2022-04-01 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0028_postlikeactivity_liker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_type', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='homeapp.post')),
                ('comment_tell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tell_comment', to='homeapp.tell')),
                ('liker_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_liker', to='homeapp.post')),
                ('liker_tell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tell_liker', to='homeapp.tell')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='homeapp.post')),
                ('tell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='homeapp.tell')),
            ],
        ),
        migrations.DeleteModel(
            name='PostLikeActivity',
        ),
    ]
