# Generated by Django 3.2.8 on 2022-04-01 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0029_auto_20220401_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tell', to='homeapp.tell'),
        ),
    ]
