# Generated by Django 3.2.8 on 2022-04-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0030_auto_20220401_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='homeapp.commentonpost'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='comment_tell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tell_comment', to='homeapp.commentontell'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='liker_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='liker_tell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tell_liker', to=settings.AUTH_USER_MODEL),
        ),
    ]
