# Generated by Django 3.2.8 on 2022-04-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0031_auto_20220401_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created']},
        ),
    ]
