# Generated by Django 3.2.8 on 2022-04-11 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0032_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commenters',
            field=models.ManyToManyField(blank=True, related_name='post_commenters', to=settings.AUTH_USER_MODEL),
        ),
    ]
