# Generated by Django 3.2.8 on 2022-04-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0034_postfeed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfeed',
            options={'ordering': ['-created'], 'verbose_name_plural': 'PostFeed'},
        ),
    ]
