# Generated by Django 4.0.4 on 2022-04-19 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0036_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-updated'], 'verbose_name_plural': 'Search'},
        ),
        migrations.AddField(
            model_name='postfeed',
            name='post_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
