# Generated by Django 4.0.4 on 2022-06-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0037_alter_search_options_postfeed_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
