# Generated by Django 4.0.4 on 2022-06-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0038_post_saved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tell',
            name='saved_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
