# Generated by Django 4.0.4 on 2022-06-04 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0039_tell_saved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='savers',
            field=models.ManyToManyField(blank=True, related_name='post_savers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tell',
            name='savers',
            field=models.ManyToManyField(blank=True, related_name='tell_savers', to=settings.AUTH_USER_MODEL),
        ),
    ]
