# Generated by Django 4.0.4 on 2022-06-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0040_post_savers_tell_savers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='saved_count',
        ),
        migrations.RemoveField(
            model_name='tell',
            name='saved_count',
        ),
    ]
