# Generated by Django 4.0.4 on 2022-06-04 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0041_remove_post_saved_count_remove_tell_saved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tellers',
            field=models.ManyToManyField(blank=True, related_name='tellers_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tell',
            name='tellers',
            field=models.ManyToManyField(blank=True, related_name='tellers_tell', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tell',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
