# Generated by Django 4.0.4 on 2022-06-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0042_post_tellers_tell_tellers_tell_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tell',
            name='tell_on_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.post'),
        ),
    ]
