# Generated by Django 4.0.4 on 2022-06-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0043_tell_tell_on_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tell',
            name='tell_on_tell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tell_on_tell_now', to='homeapp.tell'),
        ),
    ]
