# Generated by Django 4.0.4 on 2022-06-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0044_tell_tell_on_tell'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tellers_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tell',
            name='tellers_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
