# Generated by Django 4.0.4 on 2022-06-11 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0045_post_tellers_count_tell_tellers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sharers',
            field=models.ManyToManyField(blank=True, related_name='sharers_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='sharers_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tell',
            name='sharers',
            field=models.ManyToManyField(blank=True, related_name='sharers_tell', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tell',
            name='sharers_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
